name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Bye World!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start a Code
        run: echo "Starting"
      - name: Exit a Code
        run: echo "Exit"